/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutusRouteImport } from './routes/aboutus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCelebrityManagementRouteImport } from './routes/services.celebrity-management'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services.digital-marketing'
import { Route as ServicesEventManagementRouteImport } from './routes/services.event-management'
import { Route as ServicesFilmAndAdProductionRouteImport } from './routes/services.film-and-ad-production'
import { Route as ServicesFilmPromotionRouteImport } from './routes/services.film-promotion'
import { Route as ServicesProductBrandingRouteImport } from './routes/services.product-branding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusRoute = AboutusRouteImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCelebrityManagementRoute =
  ServicesCelebrityManagementRouteImport.update({
    id: '/services/celebrity-management',
    path: '/services/celebrity-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/services/digital-marketing',
    path: '/services/digital-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEventManagementRoute = ServicesEventManagementRouteImport.update({
  id: '/services/event-management',
  path: '/services/event-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFilmAndAdProductionRoute =
  ServicesFilmAndAdProductionRouteImport.update({
    id: '/services/film-and-ad-production',
    path: '/services/film-and-ad-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFilmPromotionRoute = ServicesFilmPromotionRouteImport.update({
  id: '/services/film-promotion',
  path: '/services/film-promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProductBrandingRoute = ServicesProductBrandingRouteImport.update({
  id: '/services/product-branding',
  path: '/services/product-branding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/celebrity-management': typeof ServicesCelebrityManagementRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/event-management': typeof ServicesEventManagementRoute
  '/services/film-and-ad-production': typeof ServicesFilmAndAdProductionRoute
  '/services/film-promotion': typeof ServicesFilmPromotionRoute
  '/services/product-branding': typeof ServicesProductBrandingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/celebrity-management': typeof ServicesCelebrityManagementRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/event-management': typeof ServicesEventManagementRoute
  '/services/film-and-ad-production': typeof ServicesFilmAndAdProductionRoute
  '/services/film-promotion': typeof ServicesFilmPromotionRoute
  '/services/product-branding': typeof ServicesProductBrandingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/celebrity-management': typeof ServicesCelebrityManagementRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/event-management': typeof ServicesEventManagementRoute
  '/services/film-and-ad-production': typeof ServicesFilmAndAdProductionRoute
  '/services/film-promotion': typeof ServicesFilmPromotionRoute
  '/services/product-branding': typeof ServicesProductBrandingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/contact'
    | '/portfolio'
    | '/services/celebrity-management'
    | '/services/digital-marketing'
    | '/services/event-management'
    | '/services/film-and-ad-production'
    | '/services/film-promotion'
    | '/services/product-branding'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/contact'
    | '/portfolio'
    | '/services/celebrity-management'
    | '/services/digital-marketing'
    | '/services/event-management'
    | '/services/film-and-ad-production'
    | '/services/film-promotion'
    | '/services/product-branding'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/contact'
    | '/portfolio'
    | '/services/celebrity-management'
    | '/services/digital-marketing'
    | '/services/event-management'
    | '/services/film-and-ad-production'
    | '/services/film-promotion'
    | '/services/product-branding'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusRoute: typeof AboutusRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesCelebrityManagementRoute: typeof ServicesCelebrityManagementRoute
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesEventManagementRoute: typeof ServicesEventManagementRoute
  ServicesFilmAndAdProductionRoute: typeof ServicesFilmAndAdProductionRoute
  ServicesFilmPromotionRoute: typeof ServicesFilmPromotionRoute
  ServicesProductBrandingRoute: typeof ServicesProductBrandingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/celebrity-management': {
      id: '/services/celebrity-management'
      path: '/services/celebrity-management'
      fullPath: '/services/celebrity-management'
      preLoaderRoute: typeof ServicesCelebrityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/services/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/event-management': {
      id: '/services/event-management'
      path: '/services/event-management'
      fullPath: '/services/event-management'
      preLoaderRoute: typeof ServicesEventManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/film-and-ad-production': {
      id: '/services/film-and-ad-production'
      path: '/services/film-and-ad-production'
      fullPath: '/services/film-and-ad-production'
      preLoaderRoute: typeof ServicesFilmAndAdProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/film-promotion': {
      id: '/services/film-promotion'
      path: '/services/film-promotion'
      fullPath: '/services/film-promotion'
      preLoaderRoute: typeof ServicesFilmPromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/product-branding': {
      id: '/services/product-branding'
      path: '/services/product-branding'
      fullPath: '/services/product-branding'
      preLoaderRoute: typeof ServicesProductBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusRoute: AboutusRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesCelebrityManagementRoute: ServicesCelebrityManagementRoute,
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesEventManagementRoute: ServicesEventManagementRoute,
  ServicesFilmAndAdProductionRoute: ServicesFilmAndAdProductionRoute,
  ServicesFilmPromotionRoute: ServicesFilmPromotionRoute,
  ServicesProductBrandingRoute: ServicesProductBrandingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
